# Step 4: explicit Ironic API basic-auth credentials (otherwise IrSO
# auto-generates random ones when the Ironic CR is created).
apiVersion: v1
kind: Secret
metadata:
  labels:
    environment.metal3.io/ironic-standalone-operator: "true"
  name: ironic-credentials
  namespace: baremetal-operator-system
type: kubernetes.io/basic-auth
stringData:
  username: ironic
  password: supersecret
